# This is a GitHub Actions workflow that deploys your code to PythonAnywhere.
# It runs whenever you push to the 'main' branch.

name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to PythonAnywhere
        uses: appleboy/ssh-action@v1.0.3
        with:
          # We use the API token as the password for SSH, as supported by PythonAnywhere.
          host: ssh.pythonanywhere.com
          username: ${{ secrets.PA_USERNAME }}
          password: ${{ secrets.PA_API_TOKEN }}
          port: 22
          # The script to execute on the PythonAnywhere server.
          script: |
            # Define paths
            PROJECT_DIR="/home/tongtongtong/mysite"
            VENV_DIR="/home/tongtongtong/.virtualenvs/my-cicd-venv"

            # Navigate to project directory
            cd $PROJECT_DIR
            
            echo ">>> Pulling latest code from GitHub..."
            git pull origin main
            
            # Create virtualenv if it doesn't exist
            if [ ! -d "$VENV_DIR" ]; then
              echo ">>> Creating virtualenv at $VENV_DIR..."
              python3 -m venv $VENV_DIR
            fi
            
            # Activate virtualenv and install dependencies
            echo ">>> Activating virtualenv and installing dependencies..."
            source $VENV_DIR/bin/activate
            pip install --no-cache-dir -r requirements.txt
            deactivate
            
            # Reload the web app to apply changes
            echo ">>> Reloading PythonAnywhere web app..."
            touch /var/www/tongtongtong_pythonanywhere_com_wsgi.py
            
            echo ">>> Deployment to PythonAnywhere finished successfully!"